[package]
name = "allen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
al_sys = { path = "./al-sys" }
thiserror = "1.0"
num-traits = "0.2"
num-derive = "0.3"

[dev-dependencies]
hound = "3.4.0"
